# SPDX-License-Identifier: GPL-2.0
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_INPUT_AWINIC_HAPTIC)		+= aw862x/
obj-$(CONFIG_INPUT_AWINIC_HAPTIC_NV)		+= aw862x_haptic_nv/
obj-$(CONFIG_AW869X_HAPTIC)		+= aw869x/
obj-$(CONFIG_AW869XX_HAPTIC)		+= aw869xx/
obj-$(CONFIG_AW8624_HAPTIC)		+= aw8624/
obj-$(CONFIG_AW8695_HAPTIC)		+= aw8695/
obj-$(CONFIG_AW8697_HAPTIC)		+= aw8697/
obj-$(CONFIG_AWINIC_HAPTIC_HV)		+= haptic_hv/
