# add -Wall to try to catch everything we can.
ccflags-y += -I$(srctree)/$(src)/../mmi_charger

ifneq ($(filter m y,$(CONFIG_PD_CHARGER_MMI)),)
	EXTRA_CFLAGS += -DCONFIG_PD_CHARGER_MMI
endif

obj-$(CONFIG_QPNP_SMB_BASIC_CHARGER) += qpnp_smb_basic_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
