# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_INPUT_AWINIC_HAPTIC)),)
	ccflags-y += -DCONFIG_INPUT_AWINIC_HAPTIC
endif

ifneq (,$(filter smith%,$(TARGET_PRODUCT)))
	ccflags-y += -DCONFIG_AW8697_BOOT_VIBRATION
endif

obj-$(CONFIG_AW8697_HAPTIC) += aw8697.o
