# add -Wall to try to catch everything we can.
ccflags-y += -I$(srctree)/$(src)/../mmi_charger

ifneq ($(filter m y,$(CONFIG_WIRELESS_CPS4035B)),)
	ccflags-y += -DWIRELESS_CPS4035B
endif

obj-$(CONFIG_QTI_GLINK_CHARGER) += qti_glink_charger.o
