# add -Wall to try to catch everything we can.
ccflags-y += -I$(srctree)/$(src)/../mmi_charger

ifeq ($(CONFIG_SGM4154X_CHARGER_NAME),)
	ccflags-y += -D__SGM41516D_CHIP_ID__
endif
ifeq ($(CONFIG_SGM4154X_CHARGER_NAME),sgm41541)
	ccflags-y += -D__SGM41541_CHIP_ID__
endif
ifeq ($(CONFIG_SGM4154X_CHARGER_NAME),sgm41542)
	ccflags-y += -D__SGM41542_CHIP_ID__
endif
ifeq ($(CONFIG_SGM4154X_CHARGER_NAME),sgm41516)
	ccflags-y += -D__SGM41516_CHIP_ID__
endif
ifeq ($(CONFIG_SGM4154X_CHARGER_NAME),sgm41516D)
	ccflags-y += -D__SGM41516D_CHIP_ID__
endif

obj-$(CONFIG_SGM4154X_CHARGER_LITE) += sgm4154x_charger_lite.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
