# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/power/sgm4154x_chg_mmi

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_TURBO_CHARGER)),)
        ccflags-y += -DCONFIG_MMI_QC3P_TURBO_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_WT6670_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_WT6670_DETECTED
endif

ifneq ($(filter m y,$(CONFIG_MMI_SGM41513_CHARGER)),)
        ccflags-y += -DCONFIG_MMI_SGM41513_CHARGER
endif

ifneq ($(filter m y,$(CONFIG_MMI_QC3P_Z350_DETECTED)),)
        ccflags-y += -DCONFIG_MMI_QC3P_Z350_DETECTED
endif

ifneq ($(filter m y,$(CONFIG_MMI_EXT_CHG_LED)),)
        ccflags-y += -DCONFIG_MMI_EXT_CHG_LED
endif

obj-$(CONFIG_SGM4154X_CHARGER_MMI) += sgm4154x_charger.o

