# add -Wall to try to catch everything we can.
ccflags-y += -Wall
ccflags-y += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_EGIS_PANEL_NOTIFICATIONS)),)
    ccflags-y += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_ET721_FOD)),)
    ccflags-y += -DET721_FOD
endif

rbs_fps_mmi-objs += etxxx_fp.o


obj-$(CONFIG_INPUT_EGIS_FPS_MMI) += rbs_fps_mmi.o

