# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/drivers/power/mmi_charger
EXTRA_CFLAGS += -I$(srctree)/include

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
	ccflags-y += -DMMI_GKI_API_ALLOWANCE
endif

ifneq ($(filter m y,$(CONFIG_MMI_RECHARGER_HAWAO_MODE)),)
	ccflags-y += -DCONFIG_MMI_RECHARGER_HAWAO_MODE
endif

obj-$(CONFIG_USE_MMI_CHARGER) += mmi_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
