# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/motorola/kernel/modules/include

ifneq ($(filter m y,$(CONFIG_INPUT_AWINIC_HAPTIC)),)
	ccflags-y += -DCONFIG_INPUT_AWINIC_HAPTIC
endif

ifneq (,$(filter felix%,$(TARGET_PRODUCT)))
	ccflags-y += -DHAPTIC_HV_HAL_COMPAT -DAW_DURATION_DECIDE_WAVEFORM -DAW_DURATION_WAVESEQ_2=5
endif

obj-$(CONFIG_AWINIC_HAPTIC_HV) += aw_haptic_hv.o
aw_haptic_hv-objs := aw869x.o aw869xx.o aw8671x.o aw8692x.o haptic_hv.o
